name = "AFLplusplus"
uuid = "bd9f53de-4a41-4c9e-bff2-5ae0022b6444"
authors = ["Eric P. Hanson"]
version = "1.0.0-DEV"

[deps]
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
